default_language_version:
  python: python3.9

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [ "--py39-plus" ]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.9
    -   id: black-jupyter
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: docs
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-docstring-first  # проверяет распространенную ошибку определения строки документации после кода
    -   id: check-added-large-files  # предотвращает коммит гигантских файлов
        args: [--maxkb=2048]
    -   id: check-merge-conflict # проверяет наличие файлов, содержащих конфликтные строки слияния
    -   id: check-yaml # проверяет файлы yaml на наличие разборчивого синтаксиса
    -   id: check-toml
    -   id: debug-statements # checks for debugger imports
    -   id: end-of-file-fixer # гарантирует, что файл либо пуст, либо заканчивается одной новой строкой
    -   id: trailing-whitespace # обрезает конечные пробелы
#    -   id: requirements-txt-fixer # сортирует записи в файле requirements.txt
    -   id: detect-private-key # обнаруживает наличие приватных ключей
# https://github.com/dbt-checkpoint/dbt-checkpoint для проверки моделей
